# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         KGS
version:      0.95
version_from: lib/KGS/Protocol.pm
installdirs:  site
requires:
    Audio::Data:                   0
    Audio::Play:                   0
    Compress::Zlib:                0
    Convert::Scalar:               0
    Gtk2:                          1.043
    Time::HiRes:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
